// Writes the <link rel="modulepreload"> block of index.html from the static module graph of src/main.js, so the
// browser fetches every module of the boot path in parallel instead of discovering them level by level (about
// 8 round trips deep). Re-run after adding or removing a static import: `cd tests && node make-preload.mjs`.
// perf.spec.js fails when the block is out of date.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { staticGraph, repoRoot } from './module-graph.mjs';

export const START = '<!-- modulepreload:start (generated by tests/make-preload.mjs) -->';
export const END = '<!-- modulepreload:end -->';

export function preloadBlock() {
  const files = staticGraph().filter((f) => f !== 'src/main.js');
  return [START, ...files.map((f) => `  <link rel="modulepreload" href="./${f}">`), `  ${END}`].join('\n');
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(repoRoot, 'tests/make-preload.mjs')) {
  const file = resolve(repoRoot, 'index.html');
  const html = readFileSync(file, 'utf8');
  const a = html.indexOf(START);
  const b = html.indexOf(END);
  if (a < 0 || b < 0) throw new Error('index.html has no modulepreload markers');
  writeFileSync(file, html.slice(0, a) + preloadBlock() + html.slice(b + END.length));
  console.log('modulepreload block:', staticGraph().length - 1, 'modules');
}
